[env]
TERM = "xterm-256color"

# [terminal.shell]
# program = "zellij"

[window]
padding.x = 30
padding.y = 30
decorations = "None"
opacity = 0.98
dimensions.columns = 121
dimensions.lines = 40

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]

[font]
size=12
# normal = { family = "MesloLGS NF", style = "Regular" }
# bold = { family = "MesloLGS NF", style = "Bold" }
# italic = { family = "MesloLGS NF", style = "Italic" }
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
bold = { family = "CaskaydiaCove Nerd Font Mono", style = "Bold" }
italic = { family = "CaskaydiaCove Nerd Font Mono", style = "Italic" }

[colors]
[colors.primary]
foreground = '#ffffff'
background = '#000000'


# Normal colors
[colors.normal]
black = '#32344a'
red = '#f7768e'
green = '#9ece6a'
yellow = '#e0af68'
blue = '#7aa2f7'
magenta = '#ad8ee6'
cyan = '#449dab'
white = '#787c99'

# Bright colors
[colors.bright]
black = '#444b6a'
red = '#ff7a93'
green = '#b9f27c'
yellow = '#ff9e64'
blue = '#7da6ff'
magenta = '#bb9af7'
cyan = '#0db9d7'
white = '#acb0d0'

[colors.selection]
background = '#7aa2f7'

